services:
  - type: worker
    name: majic-breaches-bot-v2
    env: node
    plan: free
    numInstances: 1
    buildCommand: "npm install"
    startCommand: "npm start"
    repo: https://github.com/RealFakeGitter/majic-breaches-bot.git
    rootDir: ./discord-bot
    autoDeploy: false
