services:
  - type: web
    name: majic-breaches-bot
    env: node
    plan: free
    buildCommand: "cd ./discord-bot && npm install"
    startCommand: "cd ./discord-bot && npm start"
    repo: https://github.com/RealFakeGitter/majic-breaches-bot.git
    rootDir: ./discord-bot
    autoDeploy: false
